name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
   
    - name: Run markdown lint
      uses: nosborn/github-action-markdown-cli@v1.1.1
      with:
        files: README.md
        config_file: ".markdownlint.json"
   
    - name: Node setup
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: Run Checklist
      shell: 'script -q -e -c "bash {0}"'
      run: npm ci && npx eslint test/. && npm run test
      